// Generated by https://quicktype.io

export interface ICompany {
    _id?:        string;
    name:        string;
    email:       string;
    description: string;
    location:    string;
    phone:       string;
    website:     string;
    password:    string;
    username:    string;
    vacancies:   string[];
    image:       string;
    banner:      string;
    token:       string;
    createdAt:   string;
    updatedAt:   string;
    __v:         number;
}
