// export interface IVacant{
//     _id             : string;
//     title           : string;
//     description     : string;
//     requirements    : IVacantRequirements;
//     location    : string;
//     salary      : number;
//     type        : 'Remoto'|'Presencial';
//     workingHour : 'Tiempo completo'|'Medio tiempo'|'Turno';

//     benefits    : string[];
//     deadline    : string;
//     image       : string;
//     views?      : number;
//     createdAt   : string;
//     company:any;
// }

// export interface IVacantRequirements{
//     experience  : string;
//     skills      : string;
//     education   : string;   
// }

// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface IVacant {
    _id?:          string;
    company?:      Company;
    title:        string;
    description:  string;
    requirements: Requirements;
    location:     string;
    salary:       number;
    type:         string;
    workingHour:  string;
    benefits:     string[];
    deadline:     string;
    image:        string;
    views?:        number;
    createdAt?:    string;
}

export interface Company {
    name:        string;
    email:       string;
    description: string;
    location:    string;
    phone:       string;
    website:     string;
    token:       string;
    username:    string;
    image:       string;
    banner:      string;
}

export interface Requirements {
    experience: string;
    skills:     string;
    education:  string;
    _id?:        string;
}
